import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CssBaseline, Box, AppBar } from "@mui/material"; 
import { ButtonMosaic } from "./(admin)/button-inicio-admin/ButtonInicioAdm"; 
import TopNavbar from "@/components/ui/top-navbar/TopNavbar";


// Importando las fuentes locales
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata para la página
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Definición del componente RootLayout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CssBaseline />
        {/* Usamos flexbox para organizar el layout */}
        <TopNavbar/>
        <Box sx={{ display: "flex", minHeight: "100vh" }}>
       
          <Box
            component="aside"
            sx={{
              width: "250px", // Sidebar de 255px de ancho
              backgroundColor: "#f0f0f0",
              p: 2,
            }}
          >
            <h2>Sidebar</h2>
            <p>Este es el espacio del sidebar.</p>
          </Box>

          {/* Contenedor derecho para ButtonInicioAdm y otros contenidos */}
          <Box
            component="main"
            sx={{
              flexGrow: 1,
              p: 2,
              backgroundColor: "#fff",
            }}
          >
            <ButtonMosaic  />
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
