import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CssBaseline, Box, AppBar } from "@mui/material"; 
import { ButtonMosaic } from "../components/ui/button-inicio-admin/ButtonInicioAdm"; 
import TopNavbar from "@/components/ui/top-navbar/TopNavbar";
import { SolicitudesEmprendedores } from "@/components/emprendedores/SolicitudesEmprendedores";
import { ListaEmprendedores } from "@/components/emprendedores/ListaEmprendedores";



// Importando las fuentes locales
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata para la página
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Definición del componente RootLayout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CssBaseline />

            <ListaEmprendedores />
            {children}
          {/* </Box>
        </Box> */}
      </body>
    </html>
  );
}
